### ISSUE TITLE
Add a Code of Conduct

### ISSUE THREAD

**Issue by vimto** [JavaScript-NZ/Society-Documentation#11] opened 2014-10-13 17:58 UTC
E.g. http://www.meetup.com/WellingtonJS/pages/The_WellingtonJS_Code_of_Conduct

**Comment by Unfocused** [comment] 2015-08-28 05:39
See also the agenda item for the upcoming AGM: https://github.com/JavaScript-NZ/Society-Meetings/issues/14

**Comment by Unfocused** [comment] 2015-09-29 04:16
https://github.com/JavaScript-NZ/Society-Documentation/pull/14

**Comment by jenofdoom** [comment] 2015-10-28 06:31
Closing this as it's a dupe of above mentioned issue

**Closed by jenofdoom** 2015-10-28 06:31 UTC
